services:
  podly:
    container_name: podly-pure-podcasts
    image: podly-pure-podcasts
    volumes:
      - ./src/instance:/app/src/instance
    env_file:
      - ./.env.local
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=${VERSION:-dev}
    ports:
      - "5003:5001"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - SERVER_THREADS=${SERVER_THREADS:-1}
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python3",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://127.0.0.1:5001/')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    name: podly-pure-podcasts-network
