# compose.dev.yml — LOCAL DEVELOPMENT
#
# Builds the image from source using the local Dockerfile. Use this when
# iterating on code changes. Runs on port 5003 to avoid conflicting with a
# production instance running on 5001.
#
# Usage:
#   docker compose -f compose.dev.yml up      # build and start
#   ./run_podly_docker.sh --dev               # wraps the above with helpers
#
# See compose.yml for pulling pre-built production images.
services:
  podly:
    container_name: podly-pure-podcasts
    image: podly-pure-podcasts
    volumes:
      - ./src/instance:/app/src/instance
    env_file:
      # Copy .env.example to .env and fill in your values before starting.
      - path: ./.env
        required: false
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=${VERSION:-dev}
    ports:
      - "5003:5001"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - SERVER_THREADS=${SERVER_THREADS:-1}
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python3",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://127.0.0.1:5001/')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    name: podly-pure-podcasts-network
