"""add llm_github_pat to llm_settings

Revision ID: c1a2b3d4e5f6
Revises: f7a4195e0953
Create Date: 2026-02-15 00:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c1a2b3d4e5f6"
down_revision = "f7a4195e0953"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("llm_github_pat", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_settings", schema=None) as batch_op:
        batch_op.drop_column("llm_github_pat")

    # ### end Alembic commands ###
